//! Inline image preview for tool results.
//!
//! `tools/image.rs::tool_generate_image` writes the generated bytes
//! into the workspace and returns "Image saved to <filename> …". The
//! chat surface picks that filename out, calls [`read_workspace_image`],
//! and renders the result as a `data:` URL inside the tool callout.
//! The command refuses paths outside the resolved workspace so a
//! hostile tool-result string can't trick the webview into reading
//! `~/.aictl/config` or anything else. `read_image` deliberately does
//! not surface a preview — keeping this command local-paths-only means
//! a malicious model output can't coerce the webview into making
//! arbitrary outbound HTTP requests on the user's behalf.

use std::path::PathBuf;

use base64::Engine;
use serde::Serialize;

use crate::workspace;

/// Hard cap on previewed bytes — DALL-E / Imagen / Grok currently top
/// out around 1.5 MB at 1024×1024, so 10 MB leaves head-room for the
/// occasional large PNG without letting a runaway file blow the IPC
/// channel.
const MAX_IMAGE_BYTES: u64 = 10 * 1024 * 1024;

#[derive(Serialize)]
pub struct WorkspaceImage {
    pub base64: String,
    pub media_type: String,
}

#[tauri::command]
pub async fn read_workspace_image(path: String) -> Result<WorkspaceImage, String> {
    let workspace = workspace::resolve()?.ok_or_else(|| "no workspace selected".to_string())?;

    let trimmed = path.trim();
    if trimmed.is_empty() {
        return Err("empty image path".to_string());
    }

    let candidate = PathBuf::from(trimmed);
    let abs = if candidate.is_absolute() {
        candidate
    } else {
        workspace.join(candidate)
    };

    let canonical = abs
        .canonicalize()
        .map_err(|e| format!("failed to resolve '{}': {e}", abs.display()))?;
    if !canonical.starts_with(&workspace) {
        return Err(format!(
            "refusing to read '{}' outside workspace",
            canonical.display()
        ));
    }

    let media_type = media_type_from_extension(&canonical)
        .ok_or_else(|| format!("'{}' is not a supported image", canonical.display()))?;

    let metadata = tokio::fs::metadata(&canonical)
        .await
        .map_err(|e| format!("failed to stat '{}': {e}", canonical.display()))?;
    if !metadata.is_file() {
        return Err(format!("'{}' is not a regular file", canonical.display()));
    }
    if metadata.len() > MAX_IMAGE_BYTES {
        return Err(format!(
            "image '{}' exceeds {}MB cap",
            canonical.display(),
            MAX_IMAGE_BYTES / (1024 * 1024)
        ));
    }

    let bytes = tokio::fs::read(&canonical)
        .await
        .map_err(|e| format!("failed to read '{}': {e}", canonical.display()))?;
    let encoded = base64::engine::general_purpose::STANDARD.encode(&bytes);
    Ok(WorkspaceImage {
        base64: encoded,
        media_type: media_type.to_string(),
    })
}

fn media_type_from_extension(path: &std::path::Path) -> Option<&'static str> {
    let ext = path.extension()?.to_ascii_lowercase();
    match ext.to_str()? {
        "png" => Some("image/png"),
        "jpg" | "jpeg" => Some("image/jpeg"),
        "gif" => Some("image/gif"),
        "webp" => Some("image/webp"),
        "bmp" => Some("image/bmp"),
        "svg" => Some("image/svg+xml"),
        _ => None,
    }
}
